#DRb Service Details
drb_hostname: localhost
drb_port: 9051

#Database connection information
adapter: oracle
database: 10.0.1.22/xe
username: prep
password: prep

#Cache details
cache_timeout: 1 #In minutes

#CallerID details
assert_type: SIPADDHEADER
#Options are:
  # - CALLERID - Using the equivalent of 'Set(CALLERID=)
  # - SIPADDHEADER - Use SipAddHeader
  # - VARIABLES - Use the channel variables ASSERTED_NAME & ASSERTED_NUMBER
from_domain: compassknowledge.com

#Details for PBX Click to Call
apply_variable_cli: FALSE #TRUE or FALSE, should always be set to false if not using PBX click to call
click_to_call_context: pbx_click_to_call #Ensure this is in the Asterisk dialplan and calls an AGI
ahn_drb_hostname: localhost
ahn_drb_port: 9050
source_technology: SIP #This is the technology to use to dial the agent
destination_technology: SIP #This is the technology to use to dial the customer
dial_trunk: avaya
dial_async: false
dial_timeout: 43200000
dial_prefix: 9
long_distance_prefix: 1

#List of NPANXXs that are not long distance, should be a regular expression and may have multiple NPANXXs
#delimtted by a pipe '|' as you may see below. The configuration file is only read at daemon start time
#so if you make a change, you must stop and start /etc/init.d/rest_webservice
exception_list: "^(407555|310555|415555)([\d]{4})$"