#DRb Service Details
drb_hostname: localhost
drb_port: 9051

#Database connection information
adapter: oracle
database: 10.0.1.22/xe
username: prep
password: prep

#Cache details
cache_timeout: 1 #In minutes

#CallerID details
assert_type: SIPADDHEADER
#Options are:
  # - CALLERID - Using the equivalent of 'Set(CALLERID=)
  # - SIPADDHEADER - Use SipAddHeader
  # - VARIABLES - Use the channel variables ASSERTED_NAME & ASSERTED_NUMBER
from_domain: compassknowledge.com

#Details for PBX Click to Call
click_to_call_context: pbx_click_to_call
ahn_drb_hostname: localhost
ahn_drb_port: 9050
channel_technology: SIP
dial_technology: SIP
dial_trunk: teliax