#!/usr/bin/env ruby
# bls This is a startup script for use in /etc/init.d
# chkconfig: 2345 90 20
# description: Used to start and stop Adhearsion daemons
 
APP_NAME = "ahn"
@default_options = {
  :name => 'presence-ahn-tools',
  :app_dir => '/opt/presence-ahn-tools/',
  :pid_file => '/var/run/presence-ahn-tools/adhearsion.pid'
}
 
def start_app
  puts "Starting #{@default_options[:name]}"
  system("/usr/bin/ruby /opt/presence-ahn-tools/adhearsion/bin/ahnctl start #{@default_options[:app_dir]} 2>&1 >> /dev/null & echo $! > #{@default_options[:pid_file]} &")
end
 
def stop_app
  pid = File.read(@default_options[:pid_file])
  puts "Stopping #{APP_NAME} with pid #{pid}"
  begin
    Process.kill(9, pid.to_i)
  rescue => err
  puts err
  end
end
 
case ARGV.first
  when 'start'
  start_app
  when 'stop'
  stop_app
  when 'restart'
  stop_app
  start_app
end
 
unless %w{start stop restart}.include? ARGV.first
  puts "Usage: #{APP_NAME} {start|stop|restart}"
  exit
end